### ISSUE TITLE
crash when run in android4.4.2 

### ISSUE THREAD

**Issue by yinjiaoyuan** [Piasy/AppRTC-Android#4]
E/AndroidRuntime(10610): Process: org.appspot.apprtc, PID: 10610
E/AndroidRuntime(10610): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.appspot.apprtc/org.appspot.apprtc.ConnectActivity}: java.lang.ClassNotFoundException: Didn't find class "org.appspot.apprtc.ConnectActivity" on path: DexPathList[[zip file "/data/app/org.appspot.apprtc-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.appspot.apprtc-1, /vendor/lib, /system/lib]]
E/AndroidRuntime(10610):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2121)
E/AndroidRuntime(10610):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
E/AndroidRuntime(10610):        at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/AndroidRuntime(10610):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/AndroidRuntime(10610):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(10610):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(10610):        at android.app.ActivityThread.main(ActivityThread.java:5030)
E/AndroidRuntime(10610):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(10610):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(10610):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime(10610):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime(10610):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(10610): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.appspot.apprtc.ConnectActivity" on path: DexPathList[[zip file "/data/app/org.appspot.apprtc-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.appspot.apprtc-1, /vendor/lib, /system/lib]]
E/AndroidRuntime(10610):        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(10610):        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/AndroidRuntime(10610):        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/AndroidRuntime(10610):        at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
E/AndroidRuntime(10610):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2112)
E/AndroidRuntime(10610):        ... 11 more
W/ActivityManager( 1959):   Force finishing activity org.appspot.apprtc/.ConnectActivity
I/Process (10610): Sending signal. PID: 10610 SIG: 9
I/ActivityManager( 1959): Process org.appspot.apprtc (pid 10610) has died.

**Comment by Piasy** [comment]
I'am not developer of webrtc, debug it yourself, good luck :)
